#!/bin/bash

###############################################################################
# ndu - Summarize disk space usage for directories
#
# Usage:
#   ./ndu [directory1 directory2 ...]
#
# Description:
#   Prints the total disk usage of each given directory (or current directory
#   if none specified) in bytes, and in kilobytes or megabytes if appropriate.
#
# Examples:
#   ./ndu /etc /var/log
#   ./ndu
###############################################################################

for dir in ${*:-.}; do
    if [ -e "$dir" ]; then
        result=$(du -s "$dir" | cut -f 1)
        let total=$result*1024
        echo -n "Total for $dir = $total bytes"
        if [ $total -ge 1048576 ]; then
            echo " ($((total/1048576)) Mb)"
        elif [ $total -ge 1024 ]; then
            echo " ($((total/1024)) Kb)"
        fi
    fi
done