#!/bin/bash
#
#        highest filename [N]
#
#        Print N highest-numbered lines in file filename.
#        The input file is assumed to have lines that start with
#        numbers.  Default for N is 10.
#

filename=$1
filename=${filename:?"missing."}
N=${2:-10}

sort -nr "$filename" | head -n "$N"